dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: mysqladmin-6528
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: mysqlmetrics-6728
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: samplesql-6327
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
