dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: sample-python-12
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: samplepython-13
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: standardmysql7-11
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: ui-custom-comp-01-11
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
