dependencies:
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: mymsql-3719
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: mysql-4820
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: mysql2-5021
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: pythonapp-3219
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: reusecomp
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: sample2-3919
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: samplemysql-5620
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: thdmf55qdb
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: xcodegitclone-4319
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
