dependencies:
- name: component1-7434
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: postgre-7635
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: pythin-http-7735
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
